module.exports = {
  container: 'ac__container',
  itemContainer: 'ac__item__container',
  item: 'ac__item',
  itemContent: 'ac__item__content',
  itemRemove: 'ac__item__remove',
  inputContainer: 'ac__input__container',
  input: 'ac__input',
  inputMirror: 'ac__input--mirror',
  inputClear: 'ac__input__clear',
  menu: 'ac__menu',
  menuItem: 'ac__menu__item',
  menuItemSelected: 'ac__menu__item--selected',
  menuItemHover: 'ac__menu__item--hover',
  menuItemText: 'ac__menu__item__text',
  menuItemRemove: 'ac__menu__item__remove',
}
