module.exports = {
  onChange: 'ac.onChange',
  onInput: 'ac.onInput',
  onInputClear: 'ac.onInputClear',
  onSelected: 'ac.onSelected',
  onUnselected: 'ac.onUnselected',
  onHoverPrev: 'ac.onHoverPrev',
  onHoverNext: 'ac.onHoverNext',
  onPressEnter: 'ac.onPressEnter',
  onPressBackspace: 'ac.onPressBackspace',
  onFocus: 'ac.onFocus',
  onRefreshMenu: 'ac.onRefreshMenu',
  onHideMenu: 'ac.onHideMenu',
  onShowMenu: 'ac.onShowMenu',
  onRemoveMenuItem: 'ac.onRemoveMenuItem',
}
